<<<<<<< HEAD
# Generated by Django 5.1.1 on 2025-06-03 18:25
=======
# Generated by Django 5.1.7 on 2025-06-09 20:14
>>>>>>> origin/main

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='nuber_of_comments',
            new_name='number_of_comments',
        ),
    ]
