# Generated by Django 5.1.1 on 2025-05-15 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_experianse_level_alter_profile_gender_and_more'),
        ('posts', '0003_remove_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(blank=True, to='accounts.profile'),
        ),
    ]
