# Generated by Django 5.1.1 on 2025-04-17 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.program')),
            ],
            options={
                'unique_together': {('exercise', 'program', 'day')},
            },
        ),        
    ]
