# Generated by Django 5.1.1 on 2025-04-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_exerciseschedule_alter_program_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseschedule',
            name='day',
            field=models.CharField(max_length=10),
        ),
    ]
