# Generated by Django 5.1.1 on 2025-04-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_alter_exerciseschedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseschedule',
            name='day',
            field=models.CharField(max_length=255),
        ),
    ]
