# Generated by Django 5.1.1 on 2025-04-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_alter_exerciseschedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseschedule',
            name='day',
            field=models.DateField(),
        ),
    ]
