# Generated by Django 5.1.1 on 2025-04-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_alter_exerciseschedule_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='exercises',
        ),
        migrations.AlterField(
            model_name='exerciseschedule',
            name='day',
            field=models.CharField(max_length=10),
        ),
    ]
