# Generated by Django 5.1.1 on 2025-04-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_remove_program_exercises_alter_exerciseschedule_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='exercises',
            field=models.ManyToManyField(related_name='programs', through='exercises.ExerciseSchedule', to='exercises.exercise'),
        ),
    ]
