# Generated by Django 5.1.1 on 2025-04-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_program_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseschedule',
            name='reps',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exerciseschedule',
            name='sets',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
    ]
