post http://127.0.0.1:8000/login/
Content-Type: application/json

  {
    "username": "your_username",
    "password": "your_password"
}

post http://127.0.0.1:8000/register/
Content-Type: application/json

  {
    "username": "your_username1",
    "password": "your_password",
    "email": "your_email2@example.com",
    "first_name": "First",
    "last_name": "Last",
    "phone": "1234567890",
    "weight": 70,
    "height": 175,
    "gender": "Male",
    "goal": "Fitness",
    "experianse_level": "Beginner",
    "user_type": "trainer"
}

post http://127.0.0.1:8000/chat/send-message/
"headers": {
  "Authorization":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyMTI3OTg2LCJpYXQiOjE3NDA1OTE5ODYsImp0aSI6ImRjNDZlMDk1ODU0YjRiNThiNmFhZTgwNDM2YzM0NTZhIiwidXNlcl9pZCI6MX0.kuN3_1e1VORnccSkP1SkWDjwZ5znQuYjh5TF-kzikZY"
},
  "body": {
  "content": "Hello, how are you?",
  "receiver_id": 2
}