POST http://127.0.0.1:8000/login/
Content-Type: application/json

{"username":"mohammed5" ,  "password":"1234"}

#######
GeT http://127.0.0.1:8000/chatapp/get-message/chat_11_12/
#######
POST http://127.0.0.1:8000/notifications/save-notification/
Content-Type: application/json

{
  "receiver":4,
  "sender": 3,
  "content": "test",
  "room_name": "1"
}
#########
POST http://127.0.0.1:8000/chatapp/save-message/
Content-Type: application/json

{
  "sender":11,
  "receiver":12,
  "content": "test",
  "room_name": "chat_1_3"
}
########
GET http://127.0.0.1:8000/notifications/user-notifications/4/
Content-Type: application/json

{}
#####
########
POST http://127.0.0.1:8000/notifications/save-notification/
Content-Type: application/json

{
  "sender": 4,
  "receiver":1,
  "content": "test",
  "room_name": "1"
}
########
GET http://127.0.0.1:8000/notifications/user-notifications/3/
Content-Type: application/json

{}
#####
### اختبار عرض التمارين حسب العضلة

GET http://127.0.0.1:8000/exercises/by-muscle/?q=arm
Accept: application/json
###

###

POST http://127.0.0.1:8000/register/
Content-Type: application/json

{"username":"manar1" , "email":"manar1@gmail.com" ,"latitude":1.33434,"longitude":0.474663, "password":"1234","phone":"1234", "weight":200.9,"height":150.6,"first_name":"jack","last_name":"jack", "gender":"male", "goal":"lose_weight", "experianse_level" :"advanced", "user_type":"trainer", "illnesses":["Heart Failure","Stroke (Prevention)"] }

###

GET http://127.0.0.1:8000/getInfo/
Content-Type: application/json
## Token instated of Bearer for normal token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgwMzkyODgzLCJpYXQiOjE3NDg4NTY4ODMsImp0aSI6IjAwYWY0NTAxMDNkZTRmODE5NWUyYjI5NWM3MDc3NDViIiwidXNlcl9pZCI6MTN9.fMPIB4sDc3TPtY3cgWTOBBbfFpcjBqirsXH_tMM8X1Y

{}
###
post http://127.0.0.1:8000/exercises/ai-program/38/
Content-Type: application/json

{}
#####
post http://127.0.0.1:8000/health/ai-program/36/
Content-Type: application/json

{}
###
DELETE http://127.0.0.1:8000/delete/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgxMTgyNjU3LCJpYXQiOjE3NDk2NDY2NTcsImp0aSI6ImU4MGI0M2FlODcwYjQ5NDhiZjA0YzBjZDNiNmVkNjdiIiwidXNlcl9pZCI6NH0.z5pUtiMcfLuSQFZfEfdBp6rRz5GsdkNajzG08C6cGZM

{}


###

Put http://127.0.0.1:8000/update_profile/
Content-Type: application/json
## Token instated of Bearer for normal token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgwMzkyODgzLCJpYXQiOjE3NDg4NTY4ODMsImp0aSI6IjAwYWY0NTAxMDNkZTRmODE5NWUyYjI5NWM3MDc3NDViIiwidXNlcl9pZCI6MTN9.fMPIB4sDc3TPtY3cgWTOBBbfFpcjBqirsXH_tMM8X1Y

{
    "field": "latitude",
    "value": 1.555555
}

###

GET http://127.0.0.1:8000/users/
Content-Type: application/json
## Token instated of Bearer for normal token
##Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2NTE3NzU5LCJpYXQiOjE3MzQ5ODE3NTksImp0aSI6IjZiMTM2OTNmMTUxMzRmMjRiNDk2ZjJjMWNjNWVkMTkzIiwidXNlcl9pZCI6ODF9.wuFvOWdUQ_WwuICdFAYoMd3GGqmZWcf0jELpCbPAzeU

{}

###

GET http://127.0.0.1:8000/coaches/
Content-Type: application/json
## Token instated of Bearer for normal token
##Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2NTE3NzU5LCJpYXQiOjE3MzQ5ODE3NTksImp0aSI6IjZiMTM2OTNmMTUxMzRmMjRiNDk2ZjJjMWNjNWVkMTkzIiwidXNlcl9pZCI6ODF9.wuFvOWdUQ_WwuICdFAYoMd3GGqmZWcf0jELpCbPAzeU

{}

###

GET http://127.0.0.1:8000/user/6/
Content-Type: application/json
## Token instated of Bearer for normal token
##Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2NTE3NzU5LCJpYXQiOjE3MzQ5ODE3NTksImp0aSI6IjZiMTM2OTNmMTUxMzRmMjRiNDk2ZjJjMWNjNWVkMTkzIiwidXNlcl9pZCI6ODF9.wuFvOWdUQ_WwuICdFAYoMd3GGqmZWcf0jELpCbPAzeU

{}


###

GET http://127.0.0.1:8000/trainers/2/
Content-Type: application/json
## Token instated of Bearer for normal token
##Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2NTE3NzU5LCJpYXQiOjE3MzQ5ODE3NTksImp0aSI6IjZiMTM2OTNmMTUxMzRmMjRiNDk2ZjJjMWNjNWVkMTkzIiwidXNlcl9pZCI6ODF9.wuFvOWdUQ_WwuICdFAYoMd3GGqmZWcf0jELpCbPAzeU

{}


###

POST http://127.0.0.1:8000/sendjoinrequest/4/2/
Content-Type: application/json
## Token instated of Bearer for normal token
##Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2NTE3NzU5LCJpYXQiOjE3MzQ5ODE3NTksImp0aSI6IjZiMTM2OTNmMTUxMzRmMjRiNDk2ZjJjMWNjNWVkMTkzIiwidXNlcl9pZCI6ODF9.wuFvOWdUQ_WwuICdFAYoMd3GGqmZWcf0jELpCbPAzeU

{}



###

POST http://127.0.0.1:8000/responsetojoinrequest/2/2/
Content-Type: application/json
## Token instated of Bearer for normal token
##Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2NTE3NzU5LCJpYXQiOjE3MzQ5ODE3NTksImp0aSI6IjZiMTM2OTNmMTUxMzRmMjRiNDk2ZjJjMWNjNWVkMTkzIiwidXNlcl9pZCI6ODF9.wuFvOWdUQ_WwuICdFAYoMd3GGqmZWcf0jELpCbPAzeU

{
    "action": "Reject"
}

###

GET http://127.0.0.1:8000/getjoinrequests/2/
Content-Type: application/json
## Token instated of Bearer for normal token
##Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2NTE3NzU5LCJpYXQiOjE3MzQ5ODE3NTksImp0aSI6IjZiMTM2OTNmMTUxMzRmMjRiNDk2ZjJjMWNjNWVkMTkzIiwidXNlcl9pZCI6ODF9.wuFvOWdUQ_WwuICdFAYoMd3GGqmZWcf0jELpCbPAzeU

{}



###

GET http://127.0.0.1:8000/exercises/listexercises/
Content-Type: application/json
## Token instated of Bearer for normal token
##Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2NTE3NzU5LCJpYXQiOjE3MzQ5ODE3NTksImp0aSI6IjZiMTM2OTNmMTUxMzRmMjRiNDk2ZjJjMWNjNWVkMTkzIiwidXNlcl9pZCI6ODF9.wuFvOWdUQ_WwuICdFAYoMd3GGqmZWcf0jELpCbPAzeU

{}

###

GET http://127.0.0.1:8000/exercises/searchexercises/
Content-Type: application/json
## Token instated of Bearer for normal token
##Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2NTE3NzU5LCJpYXQiOjE3MzQ5ODE3NTksImp0aSI6IjZiMTM2OTNmMTUxMzRmMjRiNDk2ZjJjMWNjNWVkMTkzIiwidXNlcl9pZCI6ODF9.wuFvOWdUQ_WwuICdFAYoMd3GGqmZWcf0jELpCbPAzeU

{}

###

POST http://127.0.0.1:8000/exercises/makeprogram/1/3/
Content-Type: application/json
## Token instated of Bearer for normal token
##Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2NTE3NzU5LCJpYXQiOjE3MzQ5ODE3NTksImp0aSI6IjZiMTM2OTNmMTUxMzRmMjRiNDk2ZjJjMWNjNWVkMTkzIiwidXNlcl9pZCI6ODF9.wuFvOWdUQ_WwuICdFAYoMd3GGqmZWcf0jELpCbPAzeU

{
    "description": "برنامج تدريب جديد",
    "days_exercises": [
        {
            "day": "sunday",
            "sets": 3,
            "reps": 10,
            "exercises": [2, 11]
        },
        {
            "day": "Monday",
            "sets": 3,
            "reps": 10,
            "exercises": [2, 20]
        },
        {
            "day": "Tuesday",
            "sets": 3,
            "reps": 10,
            "exercises": [20, 3]
        },
        {
            "day": "Thursday",
            "sets": 3,
            "reps": 10,
            "exercises": [4, 15]
        },
        {
            "day": "Wednesday",
            "sets": 2,
            "reps": 15,
            "exercises": [15]
        },
        {
            "day": "Friday",
            "sets": 3,
            "reps": 10,
            "exercises": [29, 12]
        }
    ]
}

###

GET http://127.0.0.1:8000/exercises/gettrainerprogram/4/
Content-Type: application/json
## Token instated of Bearer for normal token
##Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2NTE3NzU5LCJpYXQiOjE3MzQ5ODE3NTksImp0aSI6IjZiMTM2OTNmMTUxMzRmMjRiNDk2ZjJjMWNjNWVkMTkzIiwidXNlcl9pZCI6ODF9.wuFvOWdUQ_WwuICdFAYoMd3GGqmZWcf0jELpCbPAzeU

{}

###

DELETE http://127.0.0.1:8000/exercises/deleteprogram/1/3/
Content-Type: application/json
## Token instated of Bearer for normal token
##Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2NTE3NzU5LCJpYXQiOjE3MzQ5ODE3NTksImp0aSI6IjZiMTM2OTNmMTUxMzRmMjRiNDk2ZjJjMWNjNWVkMTkzIiwidXNlcl9pZCI6ODF9.wuFvOWdUQ_WwuICdFAYoMd3GGqmZWcf0jELpCbPAzeU

{}
####

DELETE http://127.0.0.1:8000/exercises/deleteprogram/program_id/user_id/
Content-Type: application/json
## Token instated of Bearer for normal token
##Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2NTE3NzU5LCJpYXQiOjE3MzQ5ODE3NTksImp0aSI6IjZiMTM2OTNmMTUxMzRmMjRiNDk2ZjJjMWNjNWVkMTkzIiwidXNlcl9pZCI6ODF9.wuFvOWdUQ_WwuICdFAYoMd3GGqmZWcf0jELpCbPAzeU

{}


###

GET http://127.0.0.1:8000/exercises/updateprogram/coach_id/program_id/
Content-Type: application/json
## Token instated of Bearer for normal token
##Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2NTE3NzU5LCJpYXQiOjE3MzQ5ODE3NTksImp0aSI6IjZiMTM2OTNmMTUxMzRmMjRiNDk2ZjJjMWNjNWVkMTkzIiwidXNlcl9pZCI6ODF9.wuFvOWdUQ_WwuICdFAYoMd3GGqmZWcf0jELpCbPAzeU

{}


###

GET http://127.0.0.1:8000/exercises/getcoachprograms/1/
Content-Type: application/json
## Token instated of Bearer for normal token
##Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2NTE3NzU5LCJpYXQiOjE3MzQ5ODE3NTksImp0aSI6IjZiMTM2OTNmMTUxMzRmMjRiNDk2ZjJjMWNjNWVkMTkzIiwidXNlcl9pZCI6ODF9.wuFvOWdUQ_WwuICdFAYoMd3GGqmZWcf0jELpCbPAzeU

{}


###

POST http://127.0.0.1:9000/posts/addpost/1/
Content-Type: application/json
## Token instated of Bearer for normal token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc3OTE4Nzk4LCJpYXQiOjE3NDYzODI3OTgsImp0aSI6ImU2Y2Y3NWYwNDEyMzQ0M2E5ZGVkMWVjYjQ1OGQxMDE3IiwidXNlcl9pZCI6Nn0.ROSJczURBaOQ5LnOQflofcbePdvRJiUWoJk3TJ5E85c

{
    "content":"hello"
}

###

POST http://127.0.0.1:8000/posts/addcomment/1/2/
Content-Type: application/json
## Token instated of Bearer for normal token
##Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2NTE3NzU5LCJpYXQiOjE3MzQ5ODE3NTksImp0aSI6IjZiMTM2OTNmMTUxMzRmMjRiNDk2ZjJjMWNjNWVkMTkzIiwidXNlcl9pZCI6ODF9.wuFvOWdUQ_WwuICdFAYoMd3GGqmZWcf0jELpCbPAzeU

{
    "text":"my post"
}

###

POST http://127.0.0.1:8000/posts/like/post_id/user_id/
Content-Type: application/json
## Token instated of Bearer for normal token
##Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2NTE3NzU5LCJpYXQiOjE3MzQ5ODE3NTksImp0aSI6IjZiMTM2OTNmMTUxMzRmMjRiNDk2ZjJjMWNjNWVkMTkzIiwidXNlcl9pZCI6ODF9.wuFvOWdUQ_WwuICdFAYoMd3GGqmZWcf0jELpCbPAzeU

{}

###

GET http://127.0.0.1:8000/posts/getallposts/
Content-Type: application/json
## Token instated of Bearer for normal token
##Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2NTE3NzU5LCJpYXQiOjE3MzQ5ODE3NTksImp0aSI6IjZiMTM2OTNmMTUxMzRmMjRiNDk2ZjJjMWNjNWVkMTkzIiwidXNlcl9pZCI6ODF9.wuFvOWdUQ_WwuICdFAYoMd3GGqmZWcf0jELpCbPAzeU

{}
###

DELETE http://127.0.0.1:8000/posts/deletepost/2/4/
Content-Type: application/json
## Token instated of Bearer for normal token
##Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2NTE3NzU5LCJpYXQiOjE3MzQ5ODE3NTksImp0aSI6IjZiMTM2OTNmMTUxMzRmMjRiNDk2ZjJjMWNjNWVkMTkzIiwidXNlcl9pZCI6ODF9.wuFvOWdUQ_WwuICdFAYoMd3GGqmZWcf0jELpCbPAzeU

{}
###

GET http://127.0.0.1:8000/posts/getcommentsonpost/1/
Content-Type: application/json
## Token instated of Bearer for normal token
##Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2NTE3NzU5LCJpYXQiOjE3MzQ5ODE3NTksImp0aSI6IjZiMTM2OTNmMTUxMzRmMjRiNDk2ZjJjMWNjNWVkMTkzIiwidXNlcl9pZCI6ODF9.wuFvOWdUQ_WwuICdFAYoMd3GGqmZWcf0jELpCbPAzeU

{}

###

Post http://127.0.0.1:8000/posts/addpost/2/
Content-Type: application/json
## Token instated of Bearer for normal token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgwNTAwNzIyLCJpYXQiOjE3NDg5NjQ3MjIsImp0aSI6ImY3NjVmNDI4YTZmMTQ3MDhhM2NlZmIxMmZhOWMwMTk0IiwidXNlcl9pZCI6Mn0.uaWuXk-PpUVAs5XuEgjmb8JeHT_Jdl4TM5M_nkD-0Mg

{
  "content":"test time"
}

###

###
GET http://127.0.0.1:8000/health/healthy-meals/
Content-Type: application/json

{}

###
GET  http://127.0.0.1:8000/health/getmealbyname/?q=Meal1
Content-Type: application/json
## Token instated of Bearer for normal token
##Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4NzM1NDE1LCJpYXQiOjE3MzcxOTk0MTUsImp0aSI6IjMzNTA5YmVhMGQ4ODRkMGNhYjkyYWQxZDNkZjVkOTQ2IiwidXNlcl9pZCI6ODF9.RuWWcpu8GLnN-Wtb02dA15czQ0-khbM18SzkLO4fR7A

{}

###
GET  http://127.0.0.1:8000/health/meal_time/?q=first meal
Content-Type: application/json
## Token instated of Bearer for normal token
##Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4NzM1NDE1LCJpYXQiOjE3MzcxOTk0MTUsImp0aSI6IjMzNTA5YmVhMGQ4ODRkMGNhYjkyYWQxZDNkZjVkOTQ2IiwidXNlcl9pZCI6ODF9.RuWWcpu8GLnN-Wtb02dA15czQ0-khbM18SzkLO4fR7A

{}

###
GET http://127.0.0.1:8000/health/foods/
Content-Type: application/json

{}

###
POST http://127.0.0.1:8000/health/addditeplan/2/1/
Content-Type: application/json

  {
    "days_meals": [
       {
           "day": "sunday",
           "description":"Hlo",
           "meals": [1]
       },
       {
           "description" : "Helo",
           "day": "sunday",
           "meals": [1]
       }
    ]
}
###

###
GET http://127.0.0.1:8000/health/coachdietplans/1/
Content-Type: application/json

{}

###
GET http://127.0.0.1:8000/health/gettrainerdietplan/1/
Content-Type: application/json

{}

###

DELETE http://127.0.0.1:8000/health/deletedietplan/5/5/
Content-Type: application/json
## Token instated of Bearer for normal token
##Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2NTE3NzU5LCJpYXQiOjE3MzQ5ODE3NTksImp0aSI6IjZiMTM2OTNmMTUxMzRmMjRiNDk2ZjJjMWNjNWVkMTkzIiwidXNlcl9pZCI6ODF9.wuFvOWdUQ_WwuICdFAYoMd3GGqmZWcf0jELpCbPAzeU

{}
###
POST http://127.0.0.1:8000/health/updatedietplan/2/5/
Content-Type: application/json
## Token instated of Bearer for normal token
##Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4NzM1NDE1LCJpYXQiOjE3MzcxOTk0MTUsImp0aSI6IjMzNTA5YmVhMGQ4ODRkMGNhYjkyYWQxZDNkZjVkOTQ2IiwidXNlcl9pZCI6ODF9.RuWWcpu8GLnN-Wtb02dA15czQ0-khbM18SzkLO4fR7A

{
    "days_meals": [
       {
           "description" : "Helo",
           "day": "sunday",
           "meals": [1,2,1]
       },
       {
           "description" : "Heo",
           "day": "Mond",
           "meals": [2]
       }
    ]
}


###
GET http://127.0.0.1:8000/health/listofretaurant/
Content-Type: application/json
## Token instated of Bearer for normal token
##Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4NzM1NDE1LCJpYXQiOjE3MzcxOTk0MTUsImp0aSI6IjMzNTA5YmVhMGQ4ODRkMGNhYjkyYWQxZDNkZjVkOTQ2IiwidXNlcl9pZCI6ODF9.RuWWcpu8GLnN-Wtb02dA15czQ0-khbM18SzkLO4fR7A

{}

###
POST http://127.0.0.1:8000/health/ordermeals/3/1/
Content-Type: application/json
## Token instated of Bearer for normal token
##Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4NzM1NDE1LCJpYXQiOjE3MzcxOTk0MTUsImp0aSI6IjMzNTA5YmVhMGQ4ODRkMGNhYjkyYWQxZDNkZjVkOTQ2IiwidXNlcl9pZCI6ODF9.RuWWcpu8GLnN-Wtb02dA15czQ0-khbM18SzkLO4fR7A

{
    "meals":[
        {
            "meal":1,
            "quantity":3
        }
    ]
}

###
PATCH  http://127.0.0.1:8000/health/updateorderstatus/2/
Content-Type: application/json
## Token instated of Bearer for normal token
##Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4NzM1NDE1LCJpYXQiOjE3MzcxOTk0MTUsImp0aSI6IjMzNTA5YmVhMGQ4ODRkMGNhYjkyYWQxZDNkZjVkOTQ2IiwidXNlcl9pZCI6ODF9.RuWWcpu8GLnN-Wtb02dA15czQ0-khbM18SzkLO4fR7A

{
    "status":"done"
}

###
GET  http://127.0.0.1:8000/health/getuserorders/3/
Content-Type: application/json
## Token instated of Bearer for normal token
##Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4NzM1NDE1LCJpYXQiOjE3MzcxOTk0MTUsImp0aSI6IjMzNTA5YmVhMGQ4ODRkMGNhYjkyYWQxZDNkZjVkOTQ2IiwidXNlcl9pZCI6ODF9.RuWWcpu8GLnN-Wtb02dA15czQ0-khbM18SzkLO4fR7A

{}

###
POST  http://127.0.0.1:8000/health/create_restaurant/
Content-Type: application/json
## Token instated of Bearer for normal token
##Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4NzM1NDE1LCJpYXQiOjE3MzcxOTk0MTUsImp0aSI6IjMzNTA5YmVhMGQ4ODRkMGNhYjkyYWQxZDNkZjVkOTQ2IiwidXNlcl9pZCI6ODF9.RuWWcpu8GLnN-Wtb02dA15czQ0-khbM18SzkLO4fR7A

{
    "name":"Restaurant1",
    "location":"Damascus",
    "latitude":1.545454,
    "longitude":12344443
}


###
POST  http://127.0.0.1:8000/health/add_food/
Content-Type: application/json
## Token instated of Bearer for normal token
##Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4NzM1NDE1LCJpYXQiOjE3MzcxOTk0MTUsImp0aSI6IjMzNTA5YmVhMGQ4ODRkMGNhYjkyYWQxZDNkZjVkOTQ2IiwidXNlcl9pZCI6ODF9.RuWWcpu8GLnN-Wtb02dA15czQ0-khbM18SzkLO4fR7A

{
    "name":"meat1",
    "calories":"75"
}

###
DELETE http://127.0.0.1:8000/health/delete-restaurants/3/
Content-Type: application/json
## Token instated of Bearer for normal token
##Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4NzM1NDE1LCJpYXQiOjE3MzcxOTk0MTUsImp0aSI6IjMzNTA5YmVhMGQ4ODRkMGNhYjkyYWQxZDNkZjVkOTQ2IiwidXNlcl9pZCI6ODF9.RuWWcpu8GLnN-Wtb02dA15czQ0-khbM18SzkLO4fR7A

###
POST  http://127.0.0.1:8000/health/create_meal/
Content-Type: application/json
## Token instated of Bearer for normal token
##Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4NzM1NDE1LCJpYXQiOjE3MzcxOTk0MTUsImp0aSI6IjMzNTA5YmVhMGQ4ODRkMGNhYjkyYWQxZDNkZjVkOTQ2IiwidXNlcl9pZCI6ODF9.RuWWcpu8GLnN-Wtb02dA15czQ0-khbM18SzkLO4fR7A

{
    "name":"meal1",
    "description":"meal1",
    "ingredients":[1],
    "price":"150",
    "restaurant":[1]
}

###
GET http://127.0.0.1:8000/health/restaurants_meal/2/
Content-Type: application/json

{}

###
GET http://127.0.0.1:8000/health/meals_in_restaurant/1/
Content-Type: application/json

{}

###
GET http://127.0.0.1:8000/getgoals/
Content-Type: application/json

{}

###
GET http://127.0.0.1:8000/getexperincelevel/
Content-Type: application/json

{}

###
GET http://127.0.0.1:8000/getrequeststatus/1/
Content-Type: application/json

{}

###
GET http://127.0.0.1:8000/gettrainerinfo/1/2/
Content-Type: application/json

{}

###
Post http://127.0.0.1:8000/exercises/makeprogram/2/1/
Content-Type: application/json

{
    "description":"first program",
    "days_exercises":[
        { 
            "day":"sunday",
            "sets":3,
            "reps":10,
            "exercises":[1,2,3] 
        },
        {
            "day":"friday",
            "sets":3,
            "reps":10,
            "exercises":[1,2,3] 
        }
    ]
}

###
Get http://127.0.0.1:8000/health/getmeal/3/
Content-Type: application/json

{
    
}

###

POST http://127.0.0.1:8000/exercises/add-exercises/
Content-Type: application/json

[
  {
    "exercise_id": 1,
    "name": "Barbell Curl",
    "muscle_group": "Biceps",
    "machine": "Barbell",
    "description": "A classic strength exercise where you lift a barbell with both hands, focusing on contracting the biceps by keeping your elbows stationary and lifting the weight toward your chest."
  },
  {
    "exercise_id": 2,
    "name": "Concentration Curl",
    "muscle_group": "Biceps",
    "machine": "Dumbbell",
    "description": "An isolation exercise performed seated, where you rest your elbow on your inner thigh and curl a dumbbell upward, targeting the biceps with strict form."
  },
  {
    "exercise_id": 3,
    "name": "Bench Press",
    "muscle_group": "Pectoralis",
    "machine": "Bench + Barbell",
    "description": "A compound exercise where you lower a barbell to your chest while lying on a bench and press it back up, primarily targeting the chest muscles."
  },
  {
    "exercise_id": 4,
    "name": "Chest Fly",
    "muscle_group": "Pectoralis",
    "machine": "Pec Deck Machine",
    "description": "A chest-isolation movement done on a pec deck machine or with dumbbells, where you bring your arms together in a hugging motion to contract the pectoral muscles."
  },
  {
    "exercise_id": 5,
    "name": "Crunches",
    "muscle_group": "Rectus Abdominis",
    "machine": "Mat",
    "description": "A bodyweight core exercise done on the floor where you lift your upper body toward your knees, targeting the front abdominal muscles."
  },
  {
    "exercise_id": 6,
    "name": "Cable Crunch",
    "muscle_group": "Rectus Abdominis",
    "machine": "Cable Machine",
    "description": "An abdominal exercise using a cable machine, where you kneel and crunch down while pulling the cable handles to activate the rectus abdominis."
  },
  {
    "exercise_id": 7,
    "name": "Lat Pulldown",
    "muscle_group": "Latissimus Dorsi",
    "machine": "Lat Pulldown Machine",
    "description": "A pulling movement where you bring a bar down toward your chest while seated, engaging the lats and upper back muscles."
  },
  {
    "exercise_id": 8,
    "name": "Pull-Ups",
    "muscle_group": "Latissimus Dorsi",
    "machine": "Pull-Up Bar",
    "description": "A bodyweight exercise where you hang from a bar and pull your chin above it, mainly working the lats and arms."
  },
  {
    "exercise_id": 9,
    "name": "Shoulder Press",
    "muscle_group": "Deltoids",
    "machine": "Dumbbell or Machine",
    "description": "A pressing movement where you lift weights overhead while seated or standing, activating the front and side deltoid muscles."
  },
  {
    "exercise_id": 10,
    "name": "Lateral Raises",
    "muscle_group": "Deltoids",
    "machine": "Dumbbell",
    "description": "An isolation exercise for the shoulders where you lift dumbbells to the side, focusing on the lateral deltoid head."
  },
  {
    "exercise_id": 11,
    "name": "Wrist Curls",
    "muscle_group": "Forearm Muscles",
    "machine": "Barbell or Dumbbell",
    "description": "A forearm-specific exercise where you sit with your forearms resting on a bench and curl your wrists upward with weights."
  },
  {
    "exercise_id": 12,
    "name": "Reverse Wrist Curl",
    "muscle_group": "Forearm Muscles",
    "machine": "Dumbbell or Barbell",
    "description": "Similar to wrist curls but performed with palms facing down to target the extensors in the forearm."
  },
  {
    "exercise_id": 13,
    "name": "Leg Extension",
    "muscle_group": "Quadriceps",
    "machine": "Leg Extension Machine",
    "description": "A quad-isolation exercise where you sit on a machine and extend your knees to lift a padded weight bar."
  },
  {
    "exercise_id": 14,
    "name": "Squat",
    "muscle_group": "Quadriceps",
    "machine": "Barbell or Smith Machine",
    "description": "A compound lower body movement where you bend the knees and lower the body, heavily engaging the quads and glutes."
   },
   {
    "exercise_id": 15,
    "name": "Leg Curl",
    "muscle_group": "Hamstrings",
    "machine": "Leg Curl Machine",
    "description": "A hamstring-targeted exercise where you lie face down and curl your legs toward your glutes against resistance."
  },
  {
    "exercise_id": 16,
    "name": "Romanian Deadlift",
    "muscle_group": "Hamstrings",
    "machine": "Barbell or Dumbbell",
    "description": "A hip hinge movement where you lower the barbell while keeping legs straight or slightly bent, emphasizing hamstring and glute engagement."
  },
  {
    "exercise_id": 17,
    "name": "Shrugs",
    "muscle_group": "Trapezius",
    "machine": "Dumbbell or Barbell",
    "description": "A simple movement where you raise your shoulders toward your ears while holding weights, focusing on the upper traps."
  },
  {
    "exercise_id": 18,
    "name": "Upright Row",
    "muscle_group": "Trapezius",
    "machine": "Barbell or Cable",
    "description": "An exercise where you pull a weight vertically to chest height with elbows out, engaging the traps and deltoids."
  },
  {
    "exercise_id": 19,
    "name": "Side Plank with Reach Through",
    "muscle_group": "Obliques",
    "machine": "Mat",
    "description": "A core stability exercise where you hold a side plank position and twist your torso to reach under your body, activating the obliques."
  },
  {
    "exercise_id": 20,
    "name": "Cable Woodchopper",
    "muscle_group": "Obliques",
    "machine": "Cable Machine",
    "description": "A rotational movement where you pull the cable from high to low or low to high across your body, engaging the oblique muscles."
  },
  {
    "exercise_id": 21,
    "name": "Running",
    "muscle_group": "Obliques",
    "machine": "Cable Machine",
    "description": "A rotational movement where you pull the cable from high to low or low to high across your body, engaging the oblique muscles."
  }
]


###
POST http://127.0.0.1:8000/illnesses/addillnesses/
Content-Type: application/json

[
 { "illness": "Peripheral Artery Disease", "foods_to_avoid": ["Fried foods", "High-sodium meals", "Sugary desserts", "Processed meats"], "sources": ["Cleveland Clinic"] },
 { "illness": "Stroke (Prevention)", "foods_to_avoid": ["Sodium-heavy foods", "Alcohol (excess)", "Red meat", "Trans fats"], "sources": ["American Stroke Association"] }
]

###
GET http://127.0.0.1:8000/illnesses/illnesses/
Content-Type: application/json

###
POST http://127.0.0.1:8000/illnesses/addillnesses_exercises/
Content-Type: application/json

[
 {
    "illness": "Hypertension (Severe)",
    "exercises_to_avoid": ["Bench Press", "Concentration Curl", "Barbell Curl"],
    "safer_alternatives": ["Walking", "Swimming", "Yoga"],
    "sources": ["American Heart Association", "Mayo Clinic"]
  },
  {
    "illness": "Heart Failure",
    "exercises_to_avoid": ["Running", "Push-ups/Sit-ups", "Sprinting"],
    "safer_alternatives": ["Stationary cycling", "Tai Chi", "Water aerobics"],
    "sources": ["NIH Heart Failure Guidelines"]
  }
]

###
GET http://127.0.0.1:8000/illnesses/illnesses_exercises/
Content-Type: application/json

###
DELETE http://127.0.0.1:8000/illnesses/deleteillness
Content-Type: application/json
#######

Get http://127.0.0.1:8000/illnesses/illnessesexercisesavoid/26/
Content-Type: application/json

##############
Get http://127.0.0.1:8000/illnesses/illnessesfoodsavoid/25/
Content-Type: application/json

#############
Get http://127.0.0.1:8000/exercises/avoidexercises/10/
Content-Type: application/json
#############
Get http://127.0.0.1:8000/health/avoidfood/10/
Content-Type: application/json

#############
Get http://127.0.0.1:8000/posts/get_nuber_of_comments/1/
Content-Type: application/json