# Generated by Django 5.1.6 on 2025-03-01 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_trainers_joinrequest'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_time',
            field=models.CharField(default=1, help_text='Time for the meal', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_Program_maker', to='accounts.profile')),
                ('meals', models.ManyToManyField(related_name='diet_plans', to='restaurants.meal')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_Program_assigned', to='accounts.profile')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients_food', to='restaurants.food'),
        ),
    ]
