# Generated by Django 5.1.7 on 2025-06-03 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('illnesses', models.JSONField(blank=True, default=list, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], default='male', max_length=15, null=True)),
                ('goal', models.CharField(blank=True, choices=[('lose_weight', 'lose_weight'), ('build_muscle', 'build_muscle'), ('endurance', 'endurance')], default='build_muscle', max_length=15, null=True)),
                ('experianse_level', models.CharField(blank=True, choices=[('beginner', 'beginner'), ('intermediate', 'intermediate'), ('advanced', 'advanced')], default='beginner', max_length=15, null=True)),
                ('user_type', models.CharField(blank=True, choices=[('coach', 'coach'), ('trainer', 'trainer')], default='trainer', max_length=15, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('trainers', models.ManyToManyField(blank=True, related_name='related_to', to='accounts.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='accounts.profile')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='accounts.profile')),
            ],
        ),
    ]
