# Generated by Django 5.1.7 on 2025-06-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='player_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
