# Generated by Django 5.1.7 on 2025-05-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_experianse_level_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='illnesses',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
