# Generated by Django 5.1.7 on 2025-05-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IllnessToAvoidFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilness', models.CharField(max_length=256)),
                ('foods_to_avoid', models.JSONField(default=list)),
                ('sources', models.JSONField(default=list)),
            ],
        ),
    ]
