# Generated by Django 5.1.7 on 2025-05-28 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('illnesses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='illnesstoavoidfood',
            old_name='ilness',
            new_name='illness',
        ),
    ]
