# Generated by Django 5.1.7 on 2025-05-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illnesses', '0002_rename_ilness_illnesstoavoidfood_illness'),
    ]

    operations = [
        migrations.CreateModel(
            name='IllnessToAvoidExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness', models.CharField(max_length=256)),
                ('exercise_to_avoid', models.JSONField(default=list)),
                ('safer_alternatives', models.JSONField(default=list)),
                ('sources', models.JSONField(default=list)),
            ],
        ),
    ]
