# Generated by Django 5.1.1 on 2025-07-27 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_receiver_and_more'),
        ('notifications', '0003_remove_notification_user_notification_receiver_and_more'),
    ]

    operations = [
    ]
